<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CarDelivery&amp;AcceptanceActApi\CarDelivery&amp;AcceptanceActApi.csproj" />
      <ProjectReference Include="..\DataAccessLayer\CarDeliveryAndAcceptance.Dal.Contracts\CarDeliveryAndAcceptance.Dal.Contracts.csproj" />
    </ItemGroup>

</Project>
